version: '3.8'
services:
  ubuntu:
    build:
      context: .
    container_name: amigadev/crosstools:ppc-amigaos
    volumes:
      - .:/work
    environment:
      - -USER=$( id -u ) -e GROUP=$( id -g )=value
